#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = 0
    while(a == 0):
        #X = random.randint(1, 10**9)  # TODO: edit here
        #Y = random.randint(1, 10**9)  # TODO: edit here
        #Z = random.randint(1, 10**9)  # TODO: edit here
        X = random.randint(-10**9, 10**9)  # TODO: edit here
        Y = random.randint(-10**9, 10**9)  # TODO: edit here
        Z = random.randint(-10**9, 10**9)  # TODO: edit here
        if(X ==  0 or Y == 0 or Z == 0):
            pass
        elif (X == Y and Y == Z and X == Z) == False:
            a = 1

    print(X, Y, Z)


if __name__ == "__main__":
    main()